/**
 * REDUX'S ACTIONS
 */

export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';
export const DASHBOARD_COMPLETE = 'DASHBOARD_COMPLETE';

export const REPORTS_START = 'REPORTS_START';
export const REPORTS_ERROR = 'REPORTS_ERROR';
export const REPORTS_COMPLETE = 'REPORTS_COMPLETE';

export const NOTIFICATIONS_START = 'NOTIFICATIONS_START';
export const NOTIFICATIONS_ERROR = 'NOTIFICATIONS_ERROR';
export const NOTIFICATIONS_COMPLETE = 'NOTIFICATIONS_COMPLETE';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';

export const CHART_DAY_START = 'CHART_DAY_START';
export const CHART_DAY_ERROR = 'CHART_DAY_ERROR';
export const CHART_DAY_COMPLETE = 'CHART_DAY_COMPLETE';

export const CHART_MONTH_START = 'CHART_MONTH_START';
export const CHART_MONTH_ERROR = 'CHART_MONTH_ERROR';
export const CHART_MONTH_COMPLETE = 'CHART_MONTH_COMPLETE';

export const SETTINGS_START = 'SETTINGS_START';
export const SETTINGS_ERROR = 'SETTINGS_ERROR';
export const SETTINGS_COMPLETE = 'SETTINGS_COMPLETE';