/**
 * REDUX'S ACTIONS
 */

export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';
export const DASHBOARD_COMPLETE = 'DASHBOARD_COMPLETE';

export const REPORTS_START = 'REPORTS_START';
export const REPORTS_ERROR = 'REPORTS_ERROR';
export const REPORTS_COMPLETE = 'REPORTS_COMPLETE';

export const NOTIFICATIONS_START = 'NOTIFICATIONS_START';
export const NOTIFICATIONS_ERROR = 'NOTIFICATIONS_ERROR';
export const NOTIFICATIONS_COMPLETE = 'NOTIFICATIONS_COMPLETE';